### ISSUE TITLE
Missing module.html file in dist

### ISSUE THREAD

**Issue by iNecas** [ryantxu/annotations-panel#1]
Thanks for nice plugin that provides functionality that I was missing in grafana.

When installing, following this steps:

1. npm install
2. npm run-script build

I was still getting issue about missing `module.html` file. Once I did `cp src/module.html dist`, everything started working: probably some missed webpack configuration, but I'm not that fluent in this stack to fix it quickly by myself.

**Comment by ryantxu** [comment]
Thanks -- issue when I converted to webpack.  Fixed in master
